### ISSUE TITLE
EPIC for page content

### ISSUE THREAD

**Issue by kltm** [kltm/reusabledata-staging#5]
- [x] make markdown-ification of all "core" data discussions:
  - [x] license-type discussion
  - [x] criteria flowchart
  - [x] bibliography/reading list
- [x] make md to html insertion tool for our static page gen
- [x] links into flow chart
- [x] automatic scoring/grading
- [x] go over main doc
  - [x] text
  - [x] pix
- [ ] fill out more pages
  - [x] about (see #60)
    - [ ] citation policy (also see footer)
    - [ ] contributors
  - [x] criteria exp
  - [x] reading list (see #59 )
  - [x] footer (@mellybelly will help here, also see #60 )
- [ ] social/forums
  - [ ] Link to Google group (do we actually have this? want this?)
  - [x] slack? (now have reusabledata.slack.com, as well as gitter for reusabledata-staging; which to use when live?)
  - [ ] twitter tags that one of us would monitor? #reusabledata?
- [ ] ensure we have all translator data sources. (not needed for first version? maybe a todo for the live site) @mellybelly where is the "full" list?
- [x] google analytics
- [x] switch to public repo
- [ ] switch to auto-deploy on merge (using bbop jenkins or travis ?)

**Comment by kltm** [comment]
Going over the text story-wise, I believe that "who we are" before "what this is" is more clear and reads a lot better.

**Comment by kltm** [comment]
This issue was moved to reusabledata/reusabledata#2
