### ISSUE TITLE
EPIC for main resource data curation

### ISSUE THREAD

**Issue by kltm** [kltm/reusabledata-staging#8]
This top-level item is to coordinate the main curation effort. Add all sources to do in alphabetical order below. There is a curation request, in double alphabetical order, by names for @jmcmurry @kltm @lrwyatt @lwinfree @mellybelly @rchampieux 

When a annotation on a resource is completed, please remember to switch `status` to `complete`.

Remember, if you find any criteria violations, you'll likely need to create a new field `license-issues`; see the schema below.

- [x] bgee-data.yaml (preliminary done by @kltm and @jmcmurry ) @jmcmurry 
- [x] bgee-ontology.yaml (preliminary done by @kltm and @jmcmurry ) @jmcmurry 
- [ ] biogrid.yaml @rchampieux 
- [ ] clinvar.yaml @rchampieux 
- [x] <strike>coriell-institute.yaml</strike> @kltm (see: https://github.com/kltm/reusabledata-staging/issues/24)
- [x] ctd.yaml @kltm
- [x] dbgap.yaml @lrwyatt 
- [x] encode.yaml @kltm
- [x] fantom5.yaml (preliminary done by @kltm and @jmcmurry ) @kltm
- [x] flybase.yaml @lrwyatt 
- [x] gtex.yaml @lrwyatt 
- [x] hpo.yaml @lrwyatt 
- [x] impc.yaml @lrwyatt 
- [x] kegg.yaml @lwinfree 
- [x] mgi.yaml @lwinfree 
- [x] mpd.yaml @lwinfree 
- [x] mygene-info.yaml @lwinfree 
- [x] ncbi-gene.yaml @kltm 
- [x] omia.yaml @kltm 
- [ ] omim.yaml @lrwyatt  (reverted to `incomplete` due to auto-grade mismatch; check curator intention: https://gitter.im/reusabledata-staging/curation?at=598e56802723db8d5e975ce0)
- [x] orphanet-open.yaml @lwinfree 
- [ ] orphanet.yaml @lwinfree 
- [x] panther.yaml @rchampieux 
- [x] reactome.yaml @rchampieux 
- [x] wormbase.yaml @rchampieux 
- [x] zfin.yaml @rchampieux 

The data resource repo is here: https://github.com/kltm/reusabledata-staging/tree/master/data-sources
I think we would prefer a PR workflow at this point. If you have questions about that, feel free to ask somebody who might know. The curation and editing should be able to be done directly through the GitHub interface, but feel free to use any method you're comfortable with.

All documents have been seeded with data from an earlier version of the Monarch data spreadsheet and may not be completely up to date, as well as any inaccuracies that I may have introduced during the port. As well, an older version of the criteria schema contained the fields `license-downstream-positive` and `license-downstream-negative`, to attempt to track license language that specifically noted downstream use. This is no longer a separate field, and items that used to be in them have all been moved to the `license-commentary` field, sometimes with a leading `+` or `-`. If you feel that the comments are not longer pertinent, are too verbose, or do not make sense, *please* feel free to remove them--if we want them back they are in the document history.

To see all the available annotation slots and some comments about their values, please see the schema here: https://github.com/kltm/reusabledata-staging/blob/master/scripts/source.schema.yaml

Usable abbreviations for many known licenses can be found here: https://spdx.org/licenses/

**Comment by kltm** [comment]
This issue was moved to reusabledata/reusabledata#3
